/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#353534",
        "on-tertiary": "#32302a",
        "on-surface": "#e5e2e1",
        "tertiary-fixed": "#e7e2d8",
        "inverse-primary": "#ae3200",
        "surface": "#131313",
        "error-container": "#93000a",
        "success": "#34d399",
        "tertiary-fixed-dim": "#cac6bd",
        "outline-variant": "#5b4038",
        "surface-container-low": "#1c1b1b",
        "silver-end": "#e8e2d5",
        "surface-bright": "#3a3939",
        "surface-container-lowest": "#0e0e0e",
        "paper-ink": "#1a1714",
        "on-error": "#690005",
        "on-secondary-container": "#afbac2",
        "on-error-container": "#ffdad6",
        "on-primary": "#5e1700",
        "on-primary-fixed-variant": "#852400",
        "mist": "#d7e2ea",
        "ember-deep": "#c2410c",
        "surface-variant": "#353534",
        "on-secondary-fixed": "#131d23",
        "surface-dim": "#131313",
        "on-secondary": "#273238",
        "on-tertiary-fixed": "#1d1c16",
        "secondary-fixed": "#d9e4ec",
        "tertiary-container": "#959289",
        "ink": "#0c0c0c",
        "on-primary-container": "#541400",
        "on-primary-fixed": "#3a0b00",
        "background": "#131313",
        "secondary": "#bdc8d0",
        "inverse-surface": "#e5e2e1",
        "ink-soft": "#141416",
        "on-surface-variant": "#e4beb3",
        "on-background": "#e5e2e1",
        "primary": "#ffb59e",
        "paper": "#ece7dd",
        "secondary-fixed-dim": "#bdc8d0",
        "secondary-container": "#404b51",
        "error": "#ffb4ab",
        "ember": "#ff5a1f",
        "on-secondary-fixed-variant": "#3e484f",
        "outline": "#ab897f",
        "surface-container-high": "#2a2a2a",
        "primary-fixed-dim": "#ffb59e",
        "inverse-on-surface": "#313030",
        "on-tertiary-fixed-variant": "#49473f",
        "on-tertiary-container": "#2d2b25",
        "primary-container": "#ff5a1f",
        "surface-tint": "#ffb59e",
        "surface-container": "#201f1f",
        "tertiary": "#cac6bd",
        "silver-start": "#5a5e66",
        "primary-fixed": "#ffdbd0",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "2.5rem",
        "stack-xs": "0.5rem",
        gutter: "1.5rem",
        "container-max": "1440px",
        "section-gap-lg": "8rem",
        "margin-mobile": "1.5rem",
        "section-gap-sm": "4rem",
        "stack-md": "1.5rem",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      fontFamily: {
        caption: ["'Be Vietnam Pro'", "sans-serif"],
        "display-hero": ["'Be Vietnam Pro'", "sans-serif"],
        h1: ["'Be Vietnam Pro'", "sans-serif"],
        "label-sm": ["'Be Vietnam Pro'", "sans-serif"],
        "display-hero-mobile": ["'Be Vietnam Pro'", "sans-serif"],
        "nav-link": ["'Be Vietnam Pro'", "sans-serif"],
        overline: ["'Be Vietnam Pro'", "sans-serif"],
        "body-md": ["'Be Vietnam Pro'", "sans-serif"],
        "body-lg": ["'Be Vietnam Pro'", "sans-serif"],
      },
      fontSize: {
        caption: ["0.65rem", { lineHeight: "1.0", letterSpacing: "0.3em", fontWeight: "400" }],
        "display-hero": ["12vw", { lineHeight: "1.0", letterSpacing: "-0.05em", fontWeight: "900" }],
        h1: ["1.5rem", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "900" }],
        "label-sm": ["0.75rem", { lineHeight: "1.0", letterSpacing: "0.15em", fontWeight: "600" }],
        "display-hero-mobile": ["3.5rem", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "900" }],
        "nav-link": ["0.875rem", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "500" }],
        overline: ["0.75rem", { lineHeight: "1.0", letterSpacing: "0.25em", fontWeight: "500" }],
        "body-md": ["1rem", { lineHeight: "1.6", letterSpacing: "0.025em", fontWeight: "300" }],
        "body-lg": ["1.25rem", { lineHeight: "1.6", letterSpacing: "0.025em", fontWeight: "300" }],
      },
    },
  },
  plugins: [],
}
